name: ATree
version: '1.2'
main: org.AzSofware.aTree.ATree
api-version: '1.21'
authors: [AzmiDe]
description: Smart TreeCapitator plugin for Paper/Spigot 1.21+

commands:
  wc:
    description: Toggle TreeCapitator on/off
    usage: /wc
    aliases: [ woodcutter, treecap ]

  aztree:
    description: Aztree plugin management
    usage: /aztree <reload>
    aliases: [ az ]

permissions:
  aztree.reload:
    description: Allows reloading the Aztree config
    default: op